<?php
$conf['coins-list'] = '#name,url/s
Ardor,https://bitbucket.org/Jelurida/ardor
Augur,https://github.com/orgs/AugurProject
Bitcoin,https://github.com/bitcoin/bitcoin
BitcoinCash,https://github.com/orgs/bitcoincashorg
Bitcoinclassic,https://github.com/orgs/bitcoinclassic
BitcoinGold,https://github.com/orgs/BTCGPU
BitcoinUnlimited,https://github.com/orgs/BitcoinUnlimited
Bitshares,https://github.com/orgs/bitshares
Blocknet,https://github.com/users/atcsecure
Cardano,https://github.com/input-output-hk/cardano-sl
Counterparty,https://github.com/orgs/CounterpartyXCP
Dash,https://github.com/orgs/dashpay
Decent,https://github.com/orgs/DECENTfoundation
DigixDAO,https://github.com/orgs/DigixGlobal
Dogecoin,https://github.com/orgs/dogecoin
Emercoin,https://github.com/orgs/Emercoin
EOS,https://github.com/orgs/EOSIO
Ethereum,https://github.com/orgs/ethereum
Ethereum Classic,https://github.com/orgs/ethereumproject
Expanse,https://github.com/orgs/expanse-org
Factom,https://github.com/orgs/FactomProject
Gnosis,https://github.com/orgs/gnosis
Golem,https://github.com/orgs/golemfactory
HyperLedger,https://github.com/orgs/hyperledger
Iota,https://github.com/orgs/iotaledger
LBRY Credits,https://github.com/orgs/lbryio
Lisk,https://github.com/orgs/LiskHQ
Litecoin,https://github.com/orgs/litecoin-project
Maidsafe,https://github.com/orgs/maidsafe
Monero,https://github.com/users/monero-project
NEM,https://github.com/orgs/NemProject
NEO,https://github.com/orgs/neo-project
Nxt,https://bitbucket.org/Jelurida/nxt
OmiseGO,https://github.com/orgs/omise
Pirl,https://github.com/orgs/pirl
PIVX,https://github.com/users/PIVX-Project
Qora,https://github.com/orgs/Qoracoin
Qtum,https://github.com/qtumproject/qtum
Ripple,https://github.com/orgs/ripple
Sia,https://github.com/NebulousLabs/Sia
Skycoin,https://github.com/orgs/skycoin
Status,https://github.com/orgs/status-im
Steem,https://github.com/orgs/steemit
Stellar Lumens,https://github.com/orgs/stellar
Storj,https://github.com/orgs/Storj
Stratis,https://github.com/orgs/stratisproject
Syscoin,https://github.com/orgs/syscoin
VCash,https://github.com/orgs/openvcash
Vertcoin,https://github.com/orgs/vertcoin
Waves,https://github.com/orgs/wavesplatform
ZCash,https://github.com/orgs/zcash'
?>
